spring.application.name=P20250709_01_userorderdemo
spring.jpa.open-in-view=false
# JWT
app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_32B
app.jwt.expiration-ms=3600000

server.port=${PORT:8080}

# CORS (ok per React in locale)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
